const state = {

  auth: {

    authenticated: false,

    player: null,

    account: null

  },


  navigation: {

    currentPath: "/",

    /*
     * Authoritative KTMS Tournament_ID currently
     * associated with the application context.
     *
     * Example of a valid KTMS value:
     * KT-2026-E01
     *
     * This value is NEVER generated by the frontend.
     */

    tournamentId: null

  },


  app: {

    initialized: false

  }

};


export function getState() {

  return state;

}


export function setAuthState(
  authState
) {

  state.auth = {

    ...state.auth,

    ...authState

  };

}


export function clearAuthState() {

  state.auth = {

    authenticated: false,

    player: null,

    account: null

  };

}


export function setCurrentPath(
  path
) {

  state.navigation.currentPath =
    path;

}


export function setTournamentContext(
  tournamentId
) {

  if (
    tournamentId === null ||
    tournamentId === undefined ||
    String(tournamentId).trim() === ""
  ) {

    state.navigation.tournamentId =
      null;

    return;

  }


  state.navigation.tournamentId =
    String(
      tournamentId
    ).trim();

}


export function clearTournamentContext() {

  state.navigation.tournamentId =
    null;

}